[package]
name = "request_watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
notify = "6.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
log = "0.4.27"
simple_logger = "5.0.0"
url = "2.5.4"
which = "7.0.3"
