[package]
name = "beech-write"
version = "0.1.0"
edition = "2021"

[dependencies]
apache-avro.workspace = true
beech-core = { path = "../beech-core" }
beech-shaper = { path = "../beech-shaper" }
itertools = "0.14.0"
sha2 = "0.10.9"
